### ISSUE TITLE
Fail to build the package with catkin build tool

### ISSUE THREAD

**Issue by petpetpeter** [UmbraTek/utra_ros#1]
I try to build the package with the catkin build tool and I found this error

![image](https://user-images.githubusercontent.com/55285546/143726213-356ac74e-dad2-4a16-82b4-dd13f20069a8.png)

I guess it's related to this discussion
https://answers.ros.org/question/50120/catkin-conversion-usrbinld-cannot-find-lpackage_name/

So, I remove the project name from every target_link_libraries  in the CMakeLists.txt file in the utra_controller package and success with the build.

from
```
target_link_libraries(joint_publisher_450 ${catkin_LIBRARIES} utra_api)
```

to

```
target_link_libraries(joint_publisher_450 ${catkin_LIBRARIES})
```

not sure if it also works for catkin_make as well.

OS Version: Ubuntu 18.04.6 LTS
ROS: Melodic

**Comment by samping** [comment]
it's have problem with some package.xml, i have updated the project. 
i make the new ubuntu 18  in VMware, and install new ros environment，
and follow the steps in readme. it can build the project.
you can try it again .
（if Gazebo not running on VMware, add "export SVGA_VGPU10=0" to ~/.bashrc）

**Comment by gmp-prem** [comment]
I tried to follow readme.md of the latest package. after that we do the catkin_make

this error from building the workspace happen like this

![Screenshot from 2021-12-22 16-30-00](https://user-images.githubusercontent.com/47204875/147053266-f2e8b3fb-01fb-4aa8-92cd-7eb54393341e.png)


OS Version: Ubuntu 18.04.6 LTS
ROS: Melodic

**Comment by samping** [comment]
it is miss the **utra_msg_generate_messages_cpp** on utra_controller CMakeLists.txt.

**Comment by samping** [comment]
please git pull the new version , and catkin_make again

**Comment by gmp-prem** [comment]
I can build the package successfully.
Now, I try "Run RViz and connect with utra" and moveit but found this error when trying to move the robot.

![error2](https://user-images.githubusercontent.com/47204875/147065627-3ff2082b-5be1-40ef-8a80-08178aea86c5.png)

The connection work fine and I could enable robot with the rviz plugin.

**Comment by gmp-prem** [comment]
thank you. it fixed by updating latest controller firmware.
