### ISSUE TITLE
Catkin build error

### ISSUE THREAD

**Issue by Hyunbin-Park** [UmbraTek/utra_ros#2]
utra_controller error occurs during catkin build.

My environment: Ubuntu 18.04 + ROS melodic + Gazebo 9.

Errors     << utra_controller:make /home/hyunbin/moveit_ws/logs/utra_controller/build.make.000.log
/usr/bin/x86_64-linux-gnu-ld: cannot find -lutra_api
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hyunbin/moveit_ws/devel/.private/utra_controller/lib/utra_controller/utra_publish] Error 1
make[1]: *** [CMakeFiles/utra_publish.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/x86_64-linux-gnu-ld: cannot find -lutra_api
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hyunbin/moveit_ws/devel/.private/utra_controller/lib/utra_controller/joint_publisher_450] Error 1
make[1]: *** [CMakeFiles/joint_publisher_450.dir/all] Error 2
/usr/bin/x86_64-linux-gnu-ld: cannot find -lutra_api
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hyunbin/moveit_ws/devel/.private/utra_controller/lib/utra_controller/joint_publisher_6] Error 1
make[1]: *** [CMakeFiles/joint_publisher_6.dir/all] Error 2
/usr/bin/x86_64-linux-gnu-ld: cannot find -lutra_api
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hyunbin/moveit_ws/devel/.private/utra_controller/lib/utra_controller/joint_trajectory_450] Error 1
make[1]: *** [CMakeFiles/joint_trajectory_450.dir/all] Error 2
/usr/bin/x86_64-linux-gnu-ld: cannot find -lutra_api
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hyunbin/moveit_ws/devel/.private/utra_controller/lib/utra_controller/utra_server] Error 1
make[1]: *** [CMakeFiles/utra_server.dir/all] Error 2
/usr/bin/x86_64-linux-gnu-ld: cannot find -lutra_api
collect2: error: ld returned 1 exit status
make[2]: *** [/home/hyunbin/moveit_ws/devel/.private/utra_controller/lib/utra_controller/joint_trajectory_6] Error 1
make[1]: *** [CMakeFiles/joint_trajectory_6.dir/all] Error 2
make: *** [all] Error 2
cd /home/hyunbin/moveit_ws/build/utra_controller; catkin build --get-env utra_controller | catkin env -si  /usr/bin/make --jobserver-fds=3,4 -j; cd -

...............................................................................
Failed     << utra_controller:make                                [ Exited with code 2 ]
Failed    <<< utra_controller                                     [ 11.6 seconds ]

**Comment by gmp-prem** [comment]
Hello! @Hyunbin-Park , I also have this problem as in [issue](https://github.com/UmbraTek/utra_ros/issues/1) issue, the umbratek company mentioned that there is a problem inside the package itself.

So, to solve this build problem, they suggest to use the **catkin_make** tool instead of the **catkin build**.

**Comment by protonnet** [comment]
Hello, @Hyunbin-Park @gmp-prem Thanks for the feedback, the latest update has fixed this issue, please update the code.

**Comment by Hyunbin-Park** [comment]
The following warning is displayed, but the build is complete.
thank you.


```
Warnings   << utra_controller:cmake /home/irl/utra_ws/logs/utra_controller/build.cmake.000.log
CMake Warning (dev) at CMakeLists.txt:58 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "utra_server_gencpp" of target "utra_server" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:41 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "utra_controller_gencpp" of target
  "joint_publisher_450" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:50 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "utra_controller_gencpp" of target
  "joint_publisher_6" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:54 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "utra_controller_gencpp" of target
  "joint_trajectory_6" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:62 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "utra_publish_gencpp" of target "utra_publish" does
  not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:45 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "utra_controller_gencpp" of target
  "joint_trajectory_450" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.


```
