### ISSUE TITLE
Effect of the incorrect joint origin position in URDF?

### ISSUE THREAD

**Issue by gmp-prem** [UmbraTek/utra_ros#3]
Hello !

**Explain the situation:** 
I just got the new robot arm series 6-550 and I'm working on setting up the manipulator arm for the pick-and-place task, so I need to start working for the environment around the robot arm because I will be using the MoveIt for motion planning and its functionality for my application.

But I noticed that the joint origin position for each link is not at the correct position (in this case, it should have been at the rotated joint position, but it is not). I have compared the URDF provided by the company with the panda robot URDF from moveit tutorial site. The panda robot's joint origin position shows out to be correctly positioned.

I have posted the image to compare between the utra 6-550 and panda robot URDF in this [link](https://github.com/gmp-prem/for-questions/tree/main/pics)

**My question is:** 
If the joint origin position of each link is not at the rotated joint for the manipulator arm, what could be the effect/problem when using the motion planning in MoveIt?

If more information is needed or words are not clear, please let me know

Thank you in advanced !

**Comment by protonnet** [comment]
HI gmp-prem.

We did make some simplification of the model, and this simplification is not affected by using moveit, the display is normal, and the kinematics of using moveit is also fine. However, there are some differences, some plugins need to use urdf files to automatically parse the relevant data may have problems: ikfast decoding urdf may not be able to parse. 

Thanks for your feedback, we'll spend some time re-optimizing this bug later.
@gmp-prem

**Comment by gmp-prem** [comment]
Hi !

Thanks for replying the issue.

If I have further question, I will create the issue

For now, I'm going to close this issue 

Thank you !
