### ISSUE TITLE
Some questions of RobotMsg in umbra rosbag

### ISSUE THREAD

**Issue by sensorwu** [UmbraTek/utra_ros#4]
Is that any explanation of RobotMsg? Such as the meaning and value of "motion_status", "motion_mode" and "tau".

**Comment by UmbraTek** [comment]
motion_mode(int): operating mode of the arm
                0: position control mode
                1: servo motion mode, users must set to this mode first before using the moveto_servoj interface.
                2: joint teaching mode
                3: cartesian teaching mode (NOT used in current version)

motion_status(int): Current running status
                1: Moving
                2: Sleeping, ready to motion
                3: Paused
                4: Stopping

tau is the current real-time output torque of the joint in N.m
