### ISSUE TITLE
How to Use real-world

### ISSUE THREAD

**Issue by jeongnow97** [UmbraTek/utra_ros#6]
I have utra6-850 and d435 depth camera

I followed most of manual you gave

I can do collision avoidance in gazebo

And I want to do it in real world

I searched about this for few weeks.. but I couldn't find meaningful result

Do you know how to do collision avoidance in real world with depth camera and real manipulator?

![img](https://github.com/UmbraTek/ut_arm_ros/assets/85015749/af6c8e11-8a0d-4263-81a1-c7777cc2b0bf)
this is what I have done

![img (1)](https://github.com/UmbraTek/ut_arm_ros/assets/85015749/eddb97dc-b6cc-40fc-8e48-1e749de78f68)
and this is the problem I face
I bring robot and depth seperately
that depth have to expressed in ocomap format and i have to fix tf
but i donn't know how to do that

**Comment by protonnet** [comment]
Hello, we have no experience in relevant cases, so we may not be able to provide support

**Comment by jeongnow97** [comment]
> Hello, we have no experience in relevant cases, so we may not be able to provide support

That's ok
I already solved myself
