### ISSUE TITLE
how to stop utarm_mvservo_trajectory from interfering with gazebo 

### ISSUE THREAD

**Issue by ghost** [UmbraTek/utra_ros#7]
Hi,

the moveit example doesn't work

when opening the rivz and gazebo without connecting the robot the model loads good

![2023-12-12 14_55_58-Window](https://github.com/UmbraTek/ut_arm_ros/assets/153611026/402227bf-2db7-4b99-9083-9a36e91e1cbe)
![2023-12-12 14_54_40-Greenshot](https://github.com/UmbraTek/ut_arm_ros/assets/153611026/5d70e669-13ad-4062-a764-d54931acb529)

but if I tried any plan it will fail and stop mid way.

if you see the (end) right of the rqt graph there is gazebo and utarm_mvservo_trajectory, both of them are trying to communicate with move_group
![rosgraph](https://github.com/UmbraTek/ut_arm_ros/assets/153611026/003571a5-9e83-4b5f-93e8-330881e92c87)

and the terminal for rivz are outputting in high speed:
`[ WARN] [1702377795.979577824, 571.252000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?`

`[ WARN] [1702377796.052882026, 571.322000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?`

`[ WARN] [1702377796.187705629, 571.454000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?`

`[ WARN] [1702377796.257843731, 571.523000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?`

`[ WARN] [1702377796.386407734, 571.652000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?`

`[ WARN] [1702377796.457298436, 571.722000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?`

`[ WARN] [1702377796.590359939, 571.853000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?`

`[ WARN] [1702377796.662512541, 571.922000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?`

`[ WARN] [1702377796.835774545, 572.052000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?`

and I think because of the 2 ActionServer racing, the execution of plans get failed and the moveit script file generates:
`[ INFO] [1702377277.165643199]: Loading robot model 'utra6_850'...`
`[ INFO] [1702377277.169364599]: No root/virtual joint specified in SRDF. Assuming fixed joint`
`[ INFO] [1702377279.107153772, 93.896000000]: Ready to take commands for planning group manipulator.`
`[ INFO] [1702377279.297062779, 94.076000000]: ABORTED: CONTROL_FAILED`
`[ INFO] [1702377282.385252694, 97.071000000]: ABORTED: CONTROL_FAILED`
`[ INFO] [1702377282.596100302, 97.276000000]: ABORTED: CONTROL_FAILED`

so what should I do?

**Comment by ghost** [comment]
the problem is gone after I killed the /utarm_mvservo_trajectory 
but I don't know what will that effect If I connected the robot. 

but now every time I plan a route. it passes by home position first then go to the desired location

**Comment by protonnet** [comment]
Hello 

What instructions were run?
Run in Rviz and Gazebo simulator if you don't have the manipulator hardware

**Comment by ghost** [comment]
Hi,

I don't have hardware, yet.
I am using gazebo and Rviz, and Rvis is using moveit -as I understand- on ros neotic on ubuntu20.04 wsl.


the instructions run/steps to repreduce: 
```bash
roslaunch utra6_850_gazebo gazebo.launch # launches gazebo and holds a terminal for warnings.
roslaunch utra6_850_moveit_config run_with_utra6_850.launch # launches rviz and moveit. and holds terminal for warnings.
# move the sphere to a new position
# press plan and succeed
# press execute to see the gazebo simulation starts moving -might even reach the point you desired- but the Rviz will output Failure state under the "Plan and Execute button" button.
# if you move the sphere to an another position and press plan you will see the Rivz planning from the home position to the new position -not from the old position to the new position-. if you pressed execute the gazebo will return to the home position first before moving to the new position.
# the terminal for rivz output the warnings at a very high speed as shown in the first post, that there is /gazebo and /utarm_mvservo_trajectory  are trying to send to the same rosnode.
#outputs:
```
```bash
[ WARN] [1702441271.301199113, 1177.462000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?
[ WARN] [1702441271.466351308, 1177.627000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?
[ WARN] [1702441271.501124307, 1177.662000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?
[ WARN] [1702441271.676016402, 1177.826000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?
[ WARN] [1702441271.714003901, 1177.861000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?
[ WARN] [1702441271.886034096, 1178.026000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?
[ WARN] [1702441271.922637295, 1178.062000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?
[ WARN] [1702441272.096813690, 1178.226000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?
[ WARN] [1702441272.136324789, 1178.260000000]: processStatus: Previously received status from [/utarm_mvservo_trajectory], but we now received status from [/gazebo]. Did the ActionServer change?
[ WARN] [1702441272.323913184, 1178.426000000]: processStatus: Previously received status from [/gazebo], but we now received status from [/utarm_mvservo_trajectory]. Did the ActionServer change?
```
 
```bash
# then trying to execute the script:
rosrun utra_ros_moveit_demo moveit_fk_demo # launches the ROS script (from https://github.com/umbratek-application/utra_ros_moveit_demo)
```
 
``` bash
# outputs:
[ INFO] [1702441197.595994756]: Loading robot model 'utra6_850'...
[ INFO] [1702441197.600717955]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1702441199.212345005, 1107.083000000]: Ready to take commands for planning group manipulator.
[ INFO] [1702441199.526976995, 1107.384000000]: ABORTED: CONTROL_FAILED
[ INFO] [1702441202.895197491, 1110.676000000]: ABORTED: CONTROL_FAILED
[ INFO] [1702441203.438504275, 1111.182000000]: ABORTED: CONTROL_FAILED
```


I have attached a txt with the full output of terminal for gazebo .
[full gazebo outputs.txt](https://github.com/UmbraTek/ut_arm_ros/files/13656136/full.gazebo.outputs.txt)

and the beginning and ending of the rivz output terminal.
[rivz output.txt](https://github.com/UmbraTek/ut_arm_ros/files/13656141/rivz.output.txt)

and the script output is as you see above.

**Comment by ghost** [comment]
uninstalling and installing everything ros related solved it.
